test-shellcheck:
  stage: test
  image: koalaman/shellcheck-alpine:stable
  needs: []
  script:
    - shellcheck src/bin/auto-deploy test/verify-application-secret test/verify-deployment-database

test-shfmt:
  stage: test
  image:
    name: mvdan/shfmt:v3.2.1-alpine
  needs: []
  script:
    - shfmt -i 2 -ci -l -d src/bin/auto-deploy test/verify-application-secret test/verify-deployment-database
